version: "2.4"
services:
  dynamo-backupper:
    env_file: .env
    build: .
    volumes:
      - ./:/src
    command: bash -c "pip3 install . && python3 ./scripts/main.py $REGION $TABLE_NAME $FOLDER_NAME"