apiVersion: batch/v1beta1
kind: CronJob # This tells kubernetes what kind of class it is working with
metadata:
  name: minion
spec:
  schedule: "0 0 * * */7" # every 5 minutes
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      parallelism: 1  # how many process in parallel I want
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: dynamo-backupper
            image: synicix/dynamo-backupper:latest
            resources:
              requests:
                cpu: 1
                memory: 2Gi
                ephemeral-storage: 2Mi
            env:
            - name: AWS_ACCESS_KEY_ID
                valueFrom:
                secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
            - name: TYPE
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: TYPE
            - name: PROJECT_ID
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: PROJECT_ID
            - name: PRIVATE_KEY_ID
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: PRIVATE_KEY_ID
            - name: PRIVATE_KEY
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: PRIVATE_KEY
            - name: CLIENT_EMAIL
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: CLIENT_EMAIL
            - name: CLIENT_ID
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: CLIENT_ID
            - name: AUTH_URI
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: AUTH_URI
            - name: TOKEN_URI
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: TOKEN_URI
            - name: AUTH_PROVIDER_x509_CERT_URL
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: AUTH_PROVIDER_x509_CERT_URL
            - name: CLIENT_x509_CERT_URL
                valueFrom:
                secretKeyRef:
                    name: google-api-credentials
                    key: CLIENT_x509_CERT_URL
            command: ["/bin/bash"]
            args: ["-c", "rm -r pipeline &&\
            git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/cajal/pipeline.git &&\
            pip3 install pipeline/python/ &&\
            git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/cajal/stimulus-pipeline.git &&\
            pip3 install stimulus-pipeline/python/ &&\
            git clone https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/cajal/stimuli.git &&\
            pip3 install stimuli/python/ &&\
            python3 /data/pipeline/python/scripts/populate-minion.py"]