apiVersion: v1 # Jobs Default K8 API
kind: Pod # This tells kubernetes what kind of class it is working with
metadata:
  name: dynamo-backupper #
  labels:
    app: dynamo-backupper
spec:
  restartPolicy: OnFailure
  volumes:
    - name: code 
      hostPath:
        path: /home/synicix/GitHub/dynamo-backupper # Directory on the host machine to be mounted
  containers: # Container Level
  - name: dynamo-backupper # Container name (Can be set to whatever)
    image: synicix/dynamo-backupper:latest # Docker Image hosted on Docker Hub
    ports:
    - containerPort: 8888
    volumeMounts: # Container reference to volumes define above
    - name: code # Name of the volume define above
      mountPath: /src #
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
    - name: TYPE
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: TYPE
    - name: PROJECT_ID
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: PROJECT_ID
    - name: PRIVATE_KEY_ID
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: PRIVATE_KEY_ID
    - name: PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: PRIVATE_KEY
    - name: CLIENT_EMAIL
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: CLIENT_EMAIL
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: CLIENT_ID
    - name: AUTH_URI
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: AUTH_URI
    - name: TOKEN_URI
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: TOKEN_URI
    - name: AUTH_PROVIDER_x509_CERT_URL
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: AUTH_PROVIDER_x509_CERT_URL
    - name: CLIENT_x509_CERT_URL
      valueFrom:
        secretKeyRef:
          name: google-api-credentials
          key: CLIENT_x509_CERT_URL
    - name: REGION
      valueFrom:
        secretKeyRef:
          name: dynamo-backupper-params
          key: REGION
    - name: TABLE_NAME
      valueFrom:
        secretKeyRef:
          name: dynamo-backupper-params
          key: TABLE_NAME
    - name: FOLDER_NAME
      valueFrom:
        secretKeyRef:
          name: dynamo-backupper-params
          key: FOLDER_NAME
    - name: GITHUB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: GITHUB_PASSWORD
    command: ["/bin/bash"] # Entry point for the container
    args: ["-c", "
    pip3 install jupyter &&\
    jupyter notebook --ip='0.0.0.0' --port=8888 --allow-root --no-browser --NotebookApp.token=${GITHUB_PASSWORD}"] # sh commands to clone and run python script

---
apiVersion: v1
kind: Service
metadata:
  name: dynamo-backupper
spec:
  type: NodePort
  selector:
    app: dynamo-backupper
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30000